#' @title Import and merge simulation data with results of analysis
#' @md
#'
#' @description Placeholder description: Merge results from PLINK assoc with
#' values used for simulation.
#' Note that paths can be specified as relative to working directory.
#'
#' @param plink_file path to the assoc or qassoc file generated by
#' \code{analysis_association()}. Include file extension.
#' @param true_effects_file path of file with true effects used in simulation,
#' including file extension.
#' The simulation functions save this file as "beta.txt".
#' @param MAFs_file path of file with true effects used in simulation,
#' including file extension.
#' The simulation functions save this file as "MAFs.txt".
#' @param alpha significance level used for single SNP tests.
#'
#' @return A tibble where true values of effects and MAFs for each SNP has been
#' merged with the results from the analysis performed by PLINK. In addition,
#' the data is augmented with the logical columns
#' * \code{causal}: \code{TRUE} if the SNP is causal for the phenotype,
#' * \code{significant}: \code{TRUE} if the effect of the SNP was significant,
#' * \code{bonferroni}: \code{TRUE} if the effect of the SNP was significant
#' with Bonferroni-correction.
#' These columns are used in in REFERENCE FUNCTIONS(error types and plots)
#'
#' @export
load_assoc_results <- function(plink_file,
                               true_effects_file,
                               MAFs_file,
                               alpha) {
  stopifnot("plink_file needs to be a valid file with extension '.assoc' or '.qassoc'" =
              (file.exists(plink_file) &&
                 (tools::file_ext(plink_file) == "assoc" ||
                    tools::file_ext(plink_file) == "qassoc")),
            "true_effects_file needs to a valid file with extension '.txt'" =
              (file.exists(true_effects_file) &&
                 tools::file_ext(true_effects_file) == "txt"),
            "MAFs_file needs to be a valid file with extension '.txt'" =
              (file.exists(MAFs_file) &&
                 tools::file_ext(MAFs_file) == "txt"),
            "alpha needs to be a number between 0 and 1" =
              (is.numeric(alpha) && 0 < alpha && alpha < 1))
  
  results <- tibble::tibble(
    data.table::fread(file = plink_file,
    header = TRUE))
  snp_effects <- tibble::tibble(
    data.table::fread(file = true_effects_file,
                      col.names = "true_effect")) %>%
    tibble::rowid_to_column("SNP")
  MAFs <- tibble::tibble(
    data.table::fread(file = MAFs_file,
                      col.names = "true_MAF")) %>%
    tibble::rowid_to_column("SNP")

  m <- nrow(results)
  merged_tbl <- dplyr::inner_join(results, snp_effects, by = "SNP") %>%
    dplyr::inner_join(MAFs, by = "SNP") %>%
    dplyr::mutate(causal = true_effect != 0,
                  significant = P < alpha,
                  bonferroni = P < alpha / m)

  return(merged_tbl)
}

#' @title Import phenotypes from simulation
#'
#' @param pheno_file path of file with phenotypes, including file extension.
#' Simulation functions save this file as "phenotypes.txt".
#'
#' @return Returns a tibble with the data from \code{pheno_file}.
#'
#' @export
load_phenotypes <- function(pheno_file) {
  pheno_ds <- tibble::tibble(data.table::fread(file = pheno_file,
                                               header = TRUE))
  return(pheno_ds)
}
